import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const themeInitializationScript = [
  "(() => {",
  "  try {",
  '    const savedTheme = localStorage.getItem("signaldesk-theme");',
  '    const systemTheme = matchMedia("(prefers-color-scheme: light)").matches',
  '      ? "light"',
  '      : "dark";',
  "    document.documentElement.dataset.theme =",
  '      savedTheme === "light" || savedTheme === "dark"',
  "        ? savedTheme",
  "        : systemTheme;",
  "  } catch {",
  '    document.documentElement.dataset.theme = "dark";',
  "  }",
  "})();",
].join("\n");

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={spaceGrotesk.variable}
      data-theme="dark"
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{ __html: themeInitializationScript }}
        />
      </head>
      <body className="flex min-h-dvh flex-col font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
